# Generated by Django 5.1.6 on 2025-03-10 09:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_location', models.CharField(max_length=50)),
                ('branch_area', models.CharField(max_length=50)),
                ('branch_phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('branch_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_firstname', models.CharField(max_length=50)),
                ('customer_lastname', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=20)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item', models.CharField(max_length=50)),
                ('cost_price', models.IntegerField()),
                ('purchased_date', models.DateField()),
                ('payment_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='inventory_images/')),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.branch')),
                ('category', models.ForeignKey(db_column='categories_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.categories')),
                ('food_item', models.ForeignKey(blank=True, db_column='food_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_username', models.CharField(max_length=50, unique=True)),
                ('staff_fullname', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=50, unique=True)),
                ('staff_password', models.CharField(max_length=128)),
                ('staff_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('staff_img', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
                ('staff_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=50)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='adminside.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.branch')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.branch')),
                ('category', models.ForeignKey(db_column='categories_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.categories')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.customer')),
                ('product', models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.inventory')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.staff')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.supplier'),
        ),
    ]
