# Generated by Django 5.1.6 on 2025-03-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
