# Generated by Django 5.1.6 on 2025-03-11 06:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_branch_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
