# Generated by Django 5.1.6 on 2025-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_staff_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
