# Generated by Django 5.1.6 on 2025-03-12 06:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_branch_branch_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
        migrations.AddField(
            model_name='purchase',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Enter a valid phone number (e.g., +919876543210).'}, max_length=128, null=True, region=None),
        ),
    ]
