# Generated by Django 5.1.6 on 2025-03-12 08:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_remove_supplier_branch_purchase_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Enter a valid phone number (e.g., +919876543210).'}, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Enter a valid phone number (e.g., +919876543210).'}, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Enter a valid phone number (e.g., +919876543210).'}, max_length=128, null=True, region=None),
        ),
    ]
