# Generated by Django 5.1.6 on 2025-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_remove_customer_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
