# Generated by Django 5.1.6 on 2025-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_rename_staff_phone_staff_staff_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('chef', 'Chef'), ('waiter', 'Waiter')], max_length=50),
        ),
    ]
