# Generated by Django 5.1.6 on 2025-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_alter_staff_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(max_length=50),
        ),
    ]
