# Generated by Django 5.1.6 on 2025-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_alter_staff_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='session_keys',
            field=models.JSONField(default=list),
        ),
    ]
