# Generated by Django 5.1.6 on 2025-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_staff_session_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_img',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to='staff_images/'),
        ),
    ]
