# Generated by Django 5.1.6 on 2025-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_alter_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_img',
            field=models.ImageField(blank=True, default='staff_images/default-profile.jpg', null=True, upload_to='staff_images/'),
        ),
    ]
