# Generated by Django 5.1.6 on 2025-03-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_alter_staff_staff_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item', models.TextField()),
                ('size', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('table', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, to='adminside.table')),
            ],
        ),
    ]
