# Generated by Django 5.1.6 on 2025-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
