# Generated by Django 5.1.6 on 2025-03-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0018_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
        ),
    ]
