# Generated by Django 5.1.6 on 2025-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=20),
        ),
    ]
