# Generated by Django 5.1.6 on 2025-03-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0022_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
