# Generated by Django 5.1.6 on 2025-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0023_remove_cart_product'),
        ('staffside', '0003_rename_created_on_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='order_list',
            field=models.ManyToManyField(to='staffside.order'),
        ),
    ]
