# Generated by Django 5.1.6 on 2025-04-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0024_salesreport_order_list'),
        ('staffside', '0003_rename_created_on_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='order_list',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='supplier',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='staffside.order'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='branch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
