# Generated by Django 5.1.6 on 2025-04-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0025_remove_salesreport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.branch'),
        ),
    ]
