# Generated by Django 5.1.6 on 2025-04-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0026_alter_salesreport_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.branch'),
        ),
    ]
