# Generated by Django 5.1.6 on 2025-04-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0029_alter_table_table_number_alter_table_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.customer'),
        ),
    ]
