# Generated by Django 5.1.6 on 2025-04-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0030_alter_salesreport_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
