# Generated by Django 5.1.6 on 2025-03-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
