# Generated by Django 5.1.6 on 2025-03-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0002_rename_created_at_order_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
