# Generated by Django 5.1.6 on 2025-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffside', '0005_order_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
